# Generated by Django 5.2.6 on 2025-11-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0002_alter_alumnos_options_alumnos_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumnos",
            name="matricula",
            field=models.CharField(max_length=12, verbose_name="Mat"),
        ),
    ]
