# Generated by Django 5.2.6 on 2025-11-12 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0003_alter_alumnos_matricula"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comentarios",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Clave"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Registrado"),
                ),
                ("coment", models.TextField(verbose_name="Comentario")),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registros.alumnos",
                        verbose_name="Alumno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentario",
                "verbose_name_plural": "Comentarios",
                "ordering": ["-created"],
            },
        ),
    ]
