# Generated by Django 5.2.6 on 2025-11-12 16:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0004_comentarios"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentarios",
            name="coment",
            field=ckeditor.fields.RichTextField(verbose_name="Comentario"),
        ),
    ]
