# Generated by Django 5.2.6 on 2025-11-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0005_alter_comentarios_coment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComentariosContcto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Clave"
                    ),
                ),
                ("usuario", models.TextField(verbose_name="Usuario")),
                ("mensaje", models.TextField(verbose_name="Comentario")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Registrado"),
                ),
            ],
            options={
                "verbose_name": "Comentario contacto",
                "verbose_name_plural": "Comentarios contactos",
                "ordering": ["-created"],
            },
        ),
    ]
