# Generated by Django 5.2.6 on 2025-11-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0006_comentarioscontcto"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ComentariosContcto",
            new_name="ComentariosContacto",
        ),
    ]
