# Generated by Django 5.2.6 on 2025-12-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registros", "0007_rename_comentarioscontcto_comentarioscontacto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Archivos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "archivo",
                    models.FileField(blank=True, null=True, upload_to="archivos"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Archivo",
                "verbose_name_plural": "Archivos",
                "ordering": ["-created"],
            },
        ),
    ]
